version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
      - 9080:15672
      - 9081:5672
      - 9082:15692
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: password